name: Build metadata from humdrum files

on:
    push:
        branches:
            - master
    workflow_dispatch: ~

jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/wolfgangdrescher/humlib:latest
            options: --user 1001

        steps:
            -
                name: Checkout
                uses: actions/checkout@v3
            -
                name: Setup node env
                uses: actions/setup-node@v3
                with:
                    node-version: 18
            -
                name: Install dependencies
                run: npm ci
            -
                name: Build metadata
                run: npm run build
            -
                name: Commit metadata
                run: |
                    git config --global user.name "Wolfgang Drescher"
                    git config --global user.email "drescher.wolfgang+git@gmail.com"
                    git diff --quiet && git diff --staged --quiet || git commit -am "Action: Build metadata"
                    git push
