name: Build commands

on:
    push:
        branches:
            - master
    workflow_dispatch: ~

jobs:
    meta:
        runs-on: ubuntu-latest

        steps:
            -
                name: Checkout
                uses: actions/checkout@v2
            -
                name: Setup node env
                uses: actions/setup-node@v2
                with:
                    node-version: 16
            -
                name: Install dependencies
                run: npm ci
            -
                name: Build meta.json
                run: npm run build
            -
                name: Commit changes
                run: |
                    git config --global user.name "Wolfgang Drescher"
                    git config --global user.email "drescher.wolfgang+git@gmail.com"
                    git diff --quiet && git diff --staged --quiet || git commit -am "Action: build meta.json"
                    git push
